substitutions:
  name: "hr-solar-vbus-wifi-2"
  friendly_name: "hr-solar-vbus-wifi-2"

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: hr-solar-vbus-wifi-2
    version: "2.0"

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github.com/surfsebas/vbus/blob/main/hr-solar-vbus-wifi-2.yaml
  import_full_config: false # or true

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.

captive_portal:

esp8266:
  board: nodemcuv2

web_server:
  port: 80
  version: 2

#mqtt:
#  broker:
#  discovery: true
#  client_id: $friendly_name

uart:
  id: resol
  rx_pin: GPIO3
  baud_rate: 9600

vbus:
  uart_id: resol

sensor:
  - platform: vbus
    model: deltasol_cs2
    temperature_1:
      name: Temperatuur Paneel # of kies een andere naam
    temperature_2:
      name: Temperatuur Tank # of kies een andere naam
    pump_speed:
      name: Pomp % # of kies een andere naam
    operating_hours:
      name: Draaiuren # of kies een andere naam
      accuracy_decimals: 0
    version:
      name: Firmware versie

binary_sensor:
  - platform: vbus
    model: deltasol_cs2
    sensor1_error:
      name: Sensor 1 Fault
    sensor2_error:
      name: Sensor 2 Fault
